### ISSUE TITLE
Floating panel and other changes

### ISSUE THREAD

**Issue by NayamAmarshe** [prateekmedia/Menu11#1]
I've been trying to take a look at Simple Menu's code and how it implements floating menu but I've been unable to do so in Menu11. I've tried several tricks but nothing seems to work and the plasmoid crashes.

Is it possible to implement the floating system from Simple Menu?

**Comment by prateekmedia** [comment]
I tried to port it from Avalon Menu but it didn't work.

And if it work I will provide an option to switch to floating or non floating behaviour as the user wish.


Also I am newbie to qml and just tinkering around to make thinks work so can you help me in below queries:
1. how to position icon after the button Like in "All Apps >" button the righ arrow icon is placed  after the text.
1. and how to make list view possible in search and all Apps screen I tried my best but it simply couldn't render it.
1. How to make leave button or shutdown button work, I tried it too but again it didn't work.

Any kind of help would be appreciated, Also is there an official app to browse the docs cause kde api is old and doesn't provide in depth documentation for things like buttons, etc.

**Comment by NayamAmarshe** [comment]
> Hey I found Out about OnzeMenu, I will port some features like floating Panel from their.
> 
> Also I am newbie to qml and just tinkering around to make thinks work so can you help me in below queries:
> 
> * [ ]  how to position icon after the button Like in "All Apps >" button the righ arrow icon is placed  after the text.
> * [ ]  and how to make list view possible in search and all Apps screen I tried my best but it simply couldn't render it.
> * [x]  ~How to make leave button or shutdown button work, I tried it too but again it didn't work.~
> 
> Any kind of help would be appreciated,
> 
> Also is there an official app to browse the docs cause kde api is old and doesn't provide in depth documentation for things like buttons, etc.

I can try looking at the icon thing. I know nothing about QML but I've been able to modify by looking at the code of other plasmoids.

**Comment by prateekmedia** [comment]
Fixed in latest Version No. 1.1

**Comment by NayamAmarshe** [comment]
@prateekmedia I have tried to make it look more like the Windows 11 menu but I'll need some help with the footer. It's pretty close.

![image](https://user-images.githubusercontent.com/25067102/124160400-d870ad00-dab9-11eb-9aec-49754f0c5bee.png)

**Comment by prateekmedia** [comment]
> @prateekmedia I have tried to make it look more like the Windows 11 menu but I'll need some help with the footer. It's pretty close.
> 
> ![image](https://user-images.githubusercontent.com/25067102/124160400-d870ad00-dab9-11eb-9aec-49754f0c5bee.png)

What kind of help?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe What kind of help?

We need to change the footer's background color to something very light. If you look at Windows 11's menu, the footer has blur and is also a teeny-tiny bit darker.
Also need to fix the divider line, it has some top margin for some reason and I was unable to fix it. The divider should be on the exact edge of the footer background.

**Comment by prateekmedia** [comment]
@NayamAmarshe How about reducing the opacity of Reactangle for Footer Background it is currently 0.2,

or maybe choose a lighter color as a background using Qt.lighter(theme.backgroundColor) as Reactangle's color

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe How about reducing the opacity of Rectangle for Footer Background it is currently 0.2,
> 
> or maybe choose a lighter color as a background using Qt.lighter(theme.backgroundColor) as Rectangle's color

I have tried that, it doesn't seem to work for some reason. I also set the color to pure white and opacity to 0 but I can't seem to get it close to Win 11's design.

**Comment by prateekmedia** [comment]
I have hardcoded colors from Windows 11

For Light theme:
Body: #E1E9FB  Footer: #D6E2F6

For Dark theme:
Body: #282828  Footer: #202020

But I don't know how to detect whether its a light theme or a dark theme.

**Comment by NayamAmarshe** [comment]
> I have the colors from Windows 11
> 
> For Light theme:
> Body: `#E1E9FB` Footer: `#D6E2F6`
> 
> For Dark theme:
> Body: `#282828 ` Footer: `#202020`
> 
> But I don't know how to detect whether its a light theme or a dark theme.
> 
> Also can you share the code with me so we can be on the same base.

Here's my code, https://github.com/NayamAmarshe/Menu11

**Comment by prateekmedia** [comment]
> > I have the colors from Windows 11
> > For Light theme:
> > Body: `#E1E9FB` Footer: `#D6E2F6`
> > For Dark theme:
> > Body: `#282828 ` Footer: `#202020`
> > But I don't know how to detect whether its a light theme or a dark theme.
> > Also can you share the code with me so we can be on the same base.
> 
> Here's my code, https://github.com/NayamAmarshe/Menu11

- [] Why hideOnWindowDeactivate is false, is it for debugging at MenuRepresentaion.qml:47
- [] All Apps / Back Button Background Color is completely white on dark theme which is annoying
- [] Can you make ItemMultiGrid Focus while searching cause user have to press down button everytime.
- [] Spacing b/w recommended and recent item Grid is very low, it should be consistent to Pinned Section

**Comment by prateekmedia** [comment]
> I'm honestly not sure about this. I'm a newbie when it comes to this.

Ok I will try to port it from MenuX then, cause it has similar functionality.

**Comment by prateekmedia** [comment]
@NayamAmarshe Also AllAppsGrid doesn't have consistent margin.

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe Also AllAppsGrid doesn't have consistent margin.

Yes, I noticed that. Can you please fix it or tell me where to look?

Also, is there any way to reduce the font size in the All Apps button?

**Comment by prateekmedia** [comment]
> > @NayamAmarshe Also AllAppsGrid doesn't have consistent margin.
> 
> Yes, I noticed that. Can you please fix it or tell me where to look?
> 
> Also, is there any way to reduce the font size in the All Apps button?

Simply set anchors.marginLeft and same for the right for allAppsGrid and runnerGrid to consistent value.

**Comment by NayamAmarshe** [comment]
I have fixed the All Apps grid and the recommended section is 1:1 to Windows 11's. However, there's a small problem I can't fix, I've tried but I just haven't been able to.
See the Pinned apps list. For some reason, I'm unable to increase the left margin, I've tried but it's not working. Also, see the right margin for the apps, it's more than what it should be. The all apps button should have larger right margin than the pinned apps on the right. 

![image](https://user-images.githubusercontent.com/25067102/124171310-04922b00-dac6-11eb-90c1-92b1f415c170.png)

**Comment by prateekmedia** [comment]
@NayamAmarshe You may have to remove some margin from allAppsGrid or runnerGrid and add it directly to the mainColumn Item b/w below lines

```qml
        anchors.margins: units.largeSpacing
        anchors.left: parent.left
```

It will work as its the Parent Widget.

**Comment by prateekmedia** [comment]
Also can you rebase your first commit, Cause merging your PR directly may end up deleting all the commit histories and contributions.

**Comment by NayamAmarshe** [comment]
> Also can you rebase your first commit, Cause merging your PR directly may end up deleting all the commit histories and contributions.

Done :)

**Comment by NayamAmarshe** [comment]
@prateekmedia  The margins have been fixed. Everything is extremely close to Win 11's menu. But I can't figure out why there's a rightMargin on the footer's background. I can't change the background either. Do you have any idea why this is happening?

![image](https://user-images.githubusercontent.com/25067102/124232003-aa798000-db2e-11eb-9210-53cc3ca8294d.png)

**Comment by prateekmedia** [comment]
@NayamAmarshe 

I have fixed it already, will soon push the code. It can be fixed by specifying rightPadding value to
```qml
    rightPadding: rightInset * 4
```

At Line 38 of the Footer.qml file

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe
> 
> I have fixed it already, will soon push the code. It can be fixed by specifying rightPadding value to
> 
> ```qml
>     rightPadding: rightInset * 4
> ```
> 
> At Line 38 of the Footer.qml file

Okay, I used another method to fix it, by shifting the parent right by 10 units, it was probably happening because of the increased width.

I have done everything I could, these are the final changes from my side :)

What can be improved now:

* [] Add a popup when you press shutdown. Show reboot, lock screen, logout, poweroff options.
* [] Fix the All Apps icon to be aligned on the right side.
* [] Reduce the font size in the All Apps button to better match 11's style.
* [] Add a very thing line on the footer's top edge, the line should be exactly on the edge.

**Comment by prateekmedia** [comment]
@NayamAmarshe I have Already done two of them :)

**Comment by prateekmedia** [comment]
Or maybe three of them :)

**Comment by NayamAmarshe** [comment]
> Or maybe three of them :)

Awesome!
I am using this image for reference btw
![Screenshot (4)](https://user-images.githubusercontent.com/25067102/124242408-596f8900-db3a-11eb-8891-f1d097571ebc.jpg)

**Comment by NayamAmarshe** [comment]
Just one more thing, the footer background still needs some fixing. The gray color kind of looks odd with the blurred background of the plasmoid. I'm not sure if this can be fixed since when I tried changing the colors, nothing happened. So it's just a minor detail that can be fixed, but not too necessary :)
 
![bloggif_60dec7e6022c9](https://user-images.githubusercontent.com/25067102/124242875-d995ee80-db3a-11eb-848a-7ed13a8ea16c.gif)

**Comment by prateekmedia** [comment]
Can you check latest Commits out, It has some more fixes and new logic for border and background for footer.

**Comment by prateekmedia** [comment]
I have your commits also pushed at 60beb919c7b63faede71d426783ecc2285424cf5, if you have other suggestions or ideas then please let me know

**Comment by NayamAmarshe** [comment]
> I have your commits also pushed at [60beb91](https://github.com/prateekmedia/Menu11/commit/60beb919c7b63faede71d426783ecc2285424cf5), if you have other suggestions or ideas then please let me know

I have 2 other commits that can be merged, I'm not sure if you have already 😅

https://github.com/NayamAmarshe/Menu11/commit/cee3c3c6ab3d05a276f46596ec847f81f2fd13ad

https://github.com/NayamAmarshe/Menu11/commit/b57dc3e6388822fb829f2bf82f24c9d1822982e1

**Comment by prateekmedia** [comment]
@NayamAmarshe 

Oops, I was working on your first commit as a base, anyways I have NayamAmarshe@cee3c3c but will add NayamAmarshe@b57dc3e, Also can you look at the commit I have made and suggest for any code changes.

Thanks!

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe
> 
> Oops, I was working on your first commit as a base, anyways I have [NayamAmarshe/Menu11@cee3c3c](https://github.com/NayamAmarshe/Menu11/commit/cee3c3c) but will add [NayamAmarshe/Menu11@b57dc3e](https://github.com/NayamAmarshe/Menu11/commit/b57dc3e), Also can you look at the commit I have made and suggest for any code changes.
> 
> Thanks!

Thanks a lot 😄

**Comment by prateekmedia** [comment]
Done! Have you tested the new version?

**Comment by prateekmedia** [comment]
@NayamAmarshe Done! Have you tested the new version?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe Done! Have you tested the new version?

Yes, I was just testing it. I noticed that the padding, width, button colors are all different. Think we're gonna have to put those back and use the values I added since they're closest to Win11's menu.

**Comment by prateekmedia** [comment]
@NayamAmarshe

I thought they were quite low size.

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe
> 
> I thought they were quite low size.

But they were made to match the exact proportions of Windows 11 menu.

**Comment by prateekmedia** [comment]
> > @NayamAmarshe
> > I thought they were quite low size.
> 
> But they were made to match the exact proportions of Windows 11 menu.
> Is it possible to use the last commit from my fork and make the footer and other changes?

Last Commit? This one NayamAmarshe/Menu11@cee3c3c, I already have that.

**Comment by NayamAmarshe** [comment]
> > > @NayamAmarshe
> > > I thought they were quite low size.
> > 
> > 
> > But they were made to match the exact proportions of Windows 11 menu.
> > Is it possible to use the last commit from my fork and make the footer and other changes?
> 
> Last Commit? This one [NayamAmarshe/Menu11@b57dc3e](https://github.com/NayamAmarshe/Menu11/commit/b57dc3e6388822fb829f2bf82f24c9d1822982e1), I already have that.

I'll try to add the changes you made, to the version I have. I think it'll be better if we use the original proportions :)

**Comment by prateekmedia** [comment]
> think

Yeah the second one is good idea, I think original proportions will work if it also work on higher displays like 1080p, 2k, 4k.

**Comment by NayamAmarshe** [comment]
@prateekmedia Sorry for the zip, I was making changes locally and forgot to set up git. I have fixed the margins, buttons, icon size and width of the plasmoid. There's only one thing left to do which I can't get to fix, The recommended text needs to pushed upwards by a bit, that's all.

[Uploading menu11.zip…]()

**Comment by NayamAmarshe** [comment]
Okay, I've pushed a commit that combines yours and my changes perfectly (not the latest ones). Forgive my stupidity, I forgot which commit of yours I cloned, but it was certainly the one from 4 hours ago.

https://github.com/NayamAmarshe/Menu11/commit/701af6eefac68f1b0182e58aa547113740b8efca

**Comment by prateekmedia** [comment]
> Okay, I've pushed a commit that combines yours and my changes perfectly (not the latest ones). Forgive my stupidity, I forgot which commit of yours I cloned, but it was certainly the one from 4 hours ago.
> 
> [NayamAmarshe@3f98cca](https://github.com/NayamAmarshe/Menu11/commit/3f98cca81528263ba9b01edf2eee19762ad0ca41)

I have already been working on your zip for 30 minutes to make it compatible and testing it and now pushed it, is there anything new in your latest commits which is different from the zip?

**Comment by NayamAmarshe** [comment]
> > Okay, I've pushed a commit that combines yours and my changes perfectly (not the latest ones). Forgive my stupidity, I forgot which commit of yours I cloned, but it was certainly the one from 4 hours ago.
> > [NayamAmarshe@3f98cca](https://github.com/NayamAmarshe/Menu11/commit/3f98cca81528263ba9b01edf2eee19762ad0ca41)
> 
> I have already been working on your zip for 30 minutes to make it compatible and testing it and now pushed it, is there anything new in your latest commits which is different from the zip?

Nope, they're both the same.

**Comment by NayamAmarshe** [comment]
Okay I tested the new version you pushed, however, it doesn't have all the changes I made. 
The app grid has more margin on left and right and between the recent files grid, there's not much space.

I'll open a PR for it so you can see the changes. Rest is all perfect.

**Comment by prateekmedia** [comment]
> Okay I tested the new version you pushed, however, it doesn't have all the changes I made.
> The app grid has more margin on left and right and between the recent files grid, there's not much space.
> 
> I'll open a PR for it so you can see the changes. Rest is all perfect.

Yes please open a PR with proper rebasing to latest version.

**Comment by NayamAmarshe** [comment]
Okay, so I cloned the latest version, made changes to it and then added a commit in my cloned project locally.
Do you know how I can create a pull request from my local commit? because If I push to main branch, it says I don't have any access to it.

**Comment by prateekmedia** [comment]
```
git remote add myrepo <--your repo url here-->
git push myrepo main --force
```

The --force is usedtto remove all the previous commits from your repo so that it doesn't give you unrelated history error.

**Comment by NayamAmarshe** [comment]
> ```shell
> git remote add myrepo <--your repo url here-->
> git push myrepo main --force
> ```
> 
> The `--force` is used to remove all the previous commits from your repo so that it doesn't give you unrelated history error.

Thanks! Done. You can check my fork.

https://github.com/NayamAmarshe/Menu11/commit/a23bc29f047d62d6bfc93af7666e5f52f2daff95

**Comment by prateekmedia** [comment]
@NayamAmarshe I will check your PR tomorrow as it's time to sleep here.

Anyways I can see some padding difference for All Apps button, why have you done that? When in All Apps screen the button looks odd.

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe I will check your PR tomorrow as it's time to sleep here.
> 
> Anyways I can see some padding difference for All Apps button, why have you done that? When in All Apps screen the button looks odd.
I suppose you're talking about the 'Back' button? That's to keep the size consistent when switching from all apps to main screen and to better match the 11 menu's buttons.

**Comment by prateekmedia** [comment]
@NayamAmarshe

Done! Included your work in 25ede4eca337d4fa1fb465f48f67297caf35d9d8

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe
> 
> Done! Included your work in [25ede4e](https://github.com/prateekmedia/Menu11/commit/25ede4eca337d4fa1fb465f48f67297caf35d9d8)

Thank you!

**Comment by NayamAmarshe** [comment]
@prateekmedia Was the footer background change in the latest version? I can see that the gray solid background is back.

**Comment by prateekmedia** [comment]
> > @NayamAmarshe
> > Done! Included your work in [25ede4e](https://github.com/prateekmedia/Menu11/commit/25ede4eca337d4fa1fb465f48f67297caf35d9d8)
> 
> Thank you!

I have change some margins in new commit due to favourites grid not being aligned properly to pinned apps and all apps, If you have any query then I will revert it.

**Comment by NayamAmarshe** [comment]
> > > @NayamAmarshe
> > > Done! Included your work in [25ede4e](https://github.com/prateekmedia/Menu11/commit/25ede4eca337d4fa1fb465f48f67297caf35d9d8)
> > 
> > 
> > Thank you!
> 
> I have change some margins in new commit due to favourites grid not being aligned properly to pinned apps and all apps, If you have any query then I will revert it.

The apps grid icons are supposed to be aligned according to Pinned label and All apps button, right on the edges, currently that's how it is on Windows 11.
How I'm doing it is using this image as my wallpaper and panel height set at 47 units. This way I'm easily able to tell the difference between Windows 11 start and Menu11. You should try it, I think it's a good way to compare :)

 https://user-images.githubusercontent.com/25067102/124242408-596f8900-db3a-11eb-8891-f1d097571ebc.jpg

**Comment by prateekmedia** [comment]
OK

**Comment by NayamAmarshe** [comment]
I think we can close this issue for now. The thread has become too long haha.
I have to say, the plasmoid looks amazing. Thank you for all the great work @prateekmedia 

![Screenshot_20210703_223334](https://user-images.githubusercontent.com/25067102/124361829-c8d69d00-dc4e-11eb-96a2-9ad206b0d2ea.png)
