### ISSUE TITLE
Can not launch Menu11

### ISSUE THREAD

**Issue by nonamewastaken** [prateekmedia/Menu11#10]
Upon clicking on the menu11 icon in my taskbar I get following error: 

```qml
file:///home/noname/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable

file:///home/noname/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:37:1: module "org.kde.plasma.private.quicklaunch" is not installed
```
I tried installing it via git and the plasma shop, which made no difference. System: latest plasma5, Arch linux

**Comment by prateekmedia** [comment]
> Upon clicking on the menu11 icon in my taskbar I get following error: "file:///home/noname/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable
> 
> file:///home/noname/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:37:1: module "org.kde.plasma.private.quicklaunch" is not installed" I tried installing it via git and the plasma shop, which made no difference. System: latest plasma5, Arch linux

Kde version? Also Do you have the latest kickoff (the redesigned one).

**Comment by prateekmedia** [comment]
As answered [here](https://askubuntu.com/questions/1250118/kde-widget-not-loading-netspeed-widget)
Do re-install this package: 
```
sudo apt-get install plasma-widgets-addons
```

**Comment by nonamewastaken** [comment]
Thanks, that fixed it. For anyone finding this in the future: The arch package name is kdeplasma-addons

**Comment by rodrigopedra** [comment]
I did reinstall the suggested package:

~~~bash
$ sudo apt-get install --reinstall plasma-widgets-addons
~~~

But am still getting this error:

~~~
file:///home/rodrigo/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable

file:///home/rodrigo/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:135:13: Type MainColumnItem unavailable

file:///home/rodrigo/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:440:5: Type Footer unavailable

file:///home/rodrigo/.local/share/plasma/plasmoids/menu11/contents/ui/Footer.qml:206:17: Cannot assign to non-existent property "size"
~~~

@prateekmedia if there is any further info I can provide to help, please let me know.

**Comment by prateekmedia** [comment]
> assign

Yeah this is the error you get when installing with git, I will push the solution now!.

**Comment by rodrigopedra** [comment]
Awesome, thanks for amazingly quick response. Thought it was a message I previously missed =)

**Comment by prateekmedia** [comment]
> Awesome, thanks for amazingly quick response. Thought it was a message I previously missed =)

Done! Enjoy, there will still be some problem with search and more button in recommended which I will fix in next commit :D.

**Comment by rodrigopedra** [comment]
Thanks again! Have a nice weekend

**Comment by Catalyst4222** [comment]
I'm getting a similar issue when clicking on the menu button
```
Error loading QML file: file:///home/nathan/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable
file:///home/nathan/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:136:13: Type MainColumnItem unavailable
file:///home/nathan/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:31:1: module "org.kde.kirigami" version 2.13 is not installed
```

**Comment by prateekmedia** [comment]
> I'm getting a similar issue when clicking on the menu button
> 
> ```
> Error loading QML file: file:///home/nathan/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable
> file:///home/nathan/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:136:13: Type MainColumnItem unavailable
> file:///home/nathan/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:31:1: module "org.kde.kirigami" version 2.13 is not installed
> ```

Just remove that line from that file,

If you still get any error in footer.qml, then change the kirigami version from 2.13 to 2.3, and report here if it occurs again.
