### ISSUE TITLE
Adjust Menu11 for 110%+ global scales

### ISSUE THREAD

**Issue by omeritzics** [prateekmedia/Menu11#13]
First, thank you for your great work!

Second, please adjust Menu11 for global scales higher than 100%, as it still needs a little adjustment.

![menu11-bug](https://user-images.githubusercontent.com/66558205/125809873-281a7135-57f3-4b55-be69-9e9014950e1a.png)

**Comment by prateekmedia** [comment]
I know this, any solutions you know?

**Comment by prateekmedia** [comment]
Ok I have fixed it, will push it in next update :).

**Comment by omeritzics** [comment]
> Ok I have fixed it, will push it in next update :).

Thank you :)

**Comment by Shiv-Patil** [comment]
`Error loading QML file: file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:137:13: Type MainColumnItem unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:533:5: Type Footer unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/Footer.qml:42:5: Cannot assign to non-existent property "background"`

Error in the latest version
