### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by yehonatan2020** [prateekmedia/Menu11#15]
Not working on Arch Linux KDE. Just gives error code when trying to open the menu

**Comment by prateekmedia** [comment]
> Not working on Arch Linux KDE. Just gives error code when trying to open the menu

Error code?

**Comment by yehonatan2020** [comment]
Sorry! There was an error loading Menu 11. file:///home/yehudi/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable

file:///home/yehudi/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:136:13: Type MainColumnItem unavailable

file:///home/yehudi/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:531:5: Type Footer unavailable

file:///home/yehudi/.local/share/plasma/plasmoids/menu11/contents/ui/Footer.qml:30:1: module "org.kde.plasma.private.quicklaunch" is not installed

**Comment by prateekmedia** [comment]
Checkout this comment for solution
https://github.com/prateekmedia/Menu11/issues/10#issuecomment-873444367

**Comment by yehonatan2020** [comment]
Package not available in arch

**Comment by prateekmedia** [comment]
> Package not available in arch

It is https://archlinux.org/packages/extra/x86_64/kdeplasma-addons/

**Comment by yehonatan2020** [comment]
i just installed this, still not working

**Comment by yehonatan2020** [comment]
BOOM! Logged out and then back in. Its now working. Thanks for the help! Thanks for the great work!

**Comment by prateekmedia** [comment]
> i just installed this, still not working

Restart your pc or login and log out, if error is different then comment that here.
