### ISSUE TITLE
Footer.qml loading error

### ISSUE THREAD

**Issue by blackPantherOS** [prateekmedia/Menu11#18]
Plasma 5.19.5

```
Error loading QML file: 
file://[...]/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable
file://[...]/menu11/contents/ui/MenuRepresentation.qml:137:13: Type MainColumnItem unavailable
file://[...]/menu11/contents/ui/MainColumnItem.qml:533:5: Type Footer unavailable
file://[...]/menu11/contents/ui/Footer.qml:43:5: Cannot assign to non-existent property "background"
```

The workaround in Footer.qml:

```
PlasmaExtras.Heading {
    id: footer
/*   
   rightPadding: rightInset
   leftPadding: rightPadding 
*/
    property Item configureButton: configureButton
    property Item avatar: avatarButton
    property int iconSize: units.iconSizes.smallMedium
    property var footerNames: ["Documents", "Pictures", "Music", "Download", "Videos", "File Manager", "System settings", "Lock screen", "Leave..."]
    property var footerIcons: ["folder-documents-symbolic", "folder-pictures-symbolic", "folder-music-symbolic", "folder-download-symbolic", "folder-videos-symbolic", "folder-symbolic", "configure", "system-lock-screen", "system-shutdown"]

/*
    background: Rectangle {
        color: Qt.lighter(theme.backgroundColor)
        border.width: 1
        border.color: Qt.darker(theme.backgroundColor, 1.14)
        radius: 5
    }
*/
    KCoreAddons.KUser {
        id: kuser
    }

```

**Comment by prateekmedia** [comment]
But with this the background of footer will be lost.

I want to keep the background + the top border to look it like windows 11.

It is only coming for old plasma I think, what is your kde plasma version?

**Comment by blackPantherOS** [comment]
> But with this the background of footer will be lost.

yes, but I think this is better, as crasing when the user try load widget.

> It is only coming for old plasma I think, what is your kde plasma version?

I write version in the first line of my report:) _Plasma 5.19.5 Framework 5.72_ the blackPanther OS (LTS) use this version

I get another issues in Menu11 "Recommend" section girdwiev on this Plasma version 

![blackPanther_20210717_121350](https://user-images.githubusercontent.com/12883566/126033776-001b882a-ee4a-4272-bc0b-e2c460a6f8f5.jpg)

I tried OnzeMenu and looks the girdview looks good
![blackPanther_20210717_122130](https://user-images.githubusercontent.com/12883566/126033958-ad21f4da-a833-4ffc-af78-3ce9864bfc55.jpg)

**Comment by prateekmedia** [comment]
Let me see what I can do

**Comment by blackPantherOS** [comment]
> Let me see what I can do

of course, thank you for your time
I think so, good solution two release, example: Menu11-1.0 for older Plasma and Menu11-2.0 newer Plasma users

**Comment by prateekmedia** [comment]
Hi, @blackPantherOS 

I have tried to fixed it, It will now work for all plasma versions can you check it.

Wakanda Forever!

**Comment by prateekmedia** [comment]
If any issue persists then please report here.
