### ISSUE TITLE
App titles don't fit

### ISSUE THREAD

**Issue by supervrijdag** [prateekmedia/Menu11#2]
If the names of the apps are too large they do not continue on the next line but become dots.

![image](https://user-images.githubusercontent.com/58634368/124261484-2248aa00-db31-11eb-9728-843aba6537ce.png)

**Windows 11:**
![image](https://user-images.githubusercontent.com/58634368/124262172-fda10200-db31-11eb-9944-c85d99b0c240.png)

**Comment by prateekmedia** [comment]
Sorry wrong issue closed

**Comment by omeritzics** [comment]
> If the names of the apps are too large they do not continue on the next line but become dots.
> 
> ![image](https://user-images.githubusercontent.com/58634368/124261484-2248aa00-db31-11eb-9728-843aba6537ce.png)
> 
> **Windows 11:**
> ![image](https://user-images.githubusercontent.com/58634368/124262172-fda10200-db31-11eb-9944-c85d99b0c240.png)

+1
And the application labels are too far from the application icons.

**Comment by prateekmedia** [comment]
@omeritzics Ok that's easy.
