### ISSUE TITLE
Can you make the user picture a little bit bigger?

### ISSUE THREAD

**Issue by aliquo93** [prateekmedia/Menu11#20]
Nice work but, as the title says, can you make the user account picture a bit bigger like in OnzeMenu [11]? Here's a link to it so you can see: https://store.kde.org/p/1545530

**Comment by prateekmedia** [comment]
Why not use OnzeMenu if you only want that feature? I tried to mimic Win11
style menu user photo.

But anyways I will try to implement it in the next few days :).

**Comment by aliquo93** [comment]
I prefer yours because is more complete than OnzeMenu! :)

**Comment by aliquo93** [comment]
Thinking about it again, i like it small, but could you make it less blurry? As you can see from the screenshots, in real Windows 11 is not blurred.

![Start](https://user-images.githubusercontent.com/9071297/126800975-35a38806-0e00-4d90-a8b1-34a4ec00b5a7.png)

![Start2](https://user-images.githubusercontent.com/9071297/126801003-f770fc2d-b22a-48ae-9862-2a2142554af3.PNG)

**Comment by prateekmedia** [comment]
What blurry, blur depends on your theme and not this applet. 

You can reduce it from
`Desktop effects -> Blur`

**Comment by aliquo93** [comment]
Disabled the blur effect and the picture is still blurry... so it depends on your applet, look more closer by zooming on the user picture in the Win11 and Linux comparison above to better understand what I mean.

Anyway, here's another screenshot with the blur effect disabled:

![blur](https://user-images.githubusercontent.com/9071297/126836905-5e4de332-a711-4de2-abeb-728b6b8f9c1f.png)

**Comment by prateekmedia** [comment]
I have tried to fix the blur and add reduce user profile size property in config which is enabled by default, you can try it out.

**Comment by aliquo93** [comment]
Now, it's better! Compliments for the good work! But why you removed the options to have the icon labels only on one line? Can't you add it back?

**Comment by prateekmedia** [comment]
@aliquo93 no it's there, https://github.com/prateekmedia/Menu11/blob/f1b56dfc3117d7196132b3dce14b8aa32bba016b/contents/ui/ConfigGeneral.qml#L254

**Comment by aliquo93** [comment]
LOL, sorry, I didn't scroll down the options.

**Comment by aliquo93** [comment]
Hi, I've translated it in Italian!

https://github.com/prateekmedia/Menu11/issues/23
