### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by aliquo93** [prateekmedia/Menu11#23]
Hi, I've translated it in Italian!

[italian.txt](https://github.com/prateekmedia/Menu11/files/6872502/italian.txt)

**Comment by aliquo93** [comment]
Please let me know when you’ll add the translation! 👍

**Comment by prateekmedia** [comment]
OK will add it till tommorow.

**Comment by prateekmedia** [comment]
OK I have added it, next time use PR if you want credit for translation in the contributors section.

**Comment by aliquo93** [comment]
Hi, I see you have added it.po, but how do I put it in my applet installation? I tought you were going to update it with a new release

**Comment by prateekmedia** [comment]
Yes I will update it in mean time, till then you could use below command:

`./translate/build.sh`

**Comment by aliquo93** [comment]
Ok, I'll wait for the update
