### ISSUE TITLE
Missing "More" button in "Recommended" section

### ISSUE THREAD

**Issue by aliquo93** [prateekmedia/Menu11#24]
![issue](https://user-images.githubusercontent.com/9071297/126875513-77fdda31-11d2-40fc-9198-18c88d79df8d.png)

**Comment by prateekmedia** [comment]
How much element do you have in recommended section or so to speak is your recommended grid scrollable?

**Comment by aliquo93** [comment]
> How much element do you have in recommended section or so to speak is your recommended grid scrollable?

I've tried to open as many app as possible but it only show the last 6, without being scrollable and without the "More" button... before v. 7.0 it was working.

**Comment by aliquo93** [comment]
UPDATE: Deleting and reinstalling the applet solved the issue, now I'll try to reapply the translation with the build script to see if it's the cause of the problem.

**Comment by aliquo93** [comment]
UPDATE 2: The problem happens if you set the recommended section to show the recent apps, if you set any of the other options the button appears.

**Comment by prateekmedia** [comment]
I think it is due to the fact that you can only have 6 apps for recent apps? Idk. I will check.

**Comment by aliquo93** [comment]
> I think it is due to the fact that you can only have 6 apps for recent apps? Idk. I will check.

Nevermind, after reinstalling I've tried again to open more apps and now it's working again. I don't know why but it wasn't working until a reinstallation.

**Comment by prateekmedia** [comment]
Look what I have found, It will only show max 6 apps I Think you can try it by logging inaand out again it should reset it to 6 max.

https://github.com/prateekmedia/Menu11/blob/471c2c646dadde1f6f40ca9c82ae8daa953f6773/contents/ui/main.qml#L116

**Comment by aliquo93** [comment]
Yes it show 6 apps, but before reinstalling the “More” buttons wasn’t appearing even if I had more than 6 recent apps... after the reinstallation it started to work again.
