### ISSUE TITLE
profile image and powermenu not centered

### ISSUE THREAD

**Issue by xeome** [prateekmedia/Menu11#31]
as shown bellow menu11 profile image isnt centered
(the bottom image is actual win11)
![menu11](https://user-images.githubusercontent.com/44901648/129382093-54b533df-00aa-4ab7-a152-575f2f38a3d8.png)
![win11](https://user-images.githubusercontent.com/44901648/129382096-fb58b39f-6cba-442c-a976-2b9db36e1331.png)

**Comment by prateekmedia** [comment]
Actually it is ceetred but is dependent on the theme you use. Like it will be centered on Breeze theme.
