### ISSUE TITLE
Wrong icons used for full size pinned apps

### ISSUE THREAD

**Issue by SubwayRunner** [prateekmedia/Menu11#35]
It looks like pinned apps use icons that are meant for tray icons in icon themes.

How the icon looks:
![Screenshot_20210903_123245](https://user-images.githubusercontent.com/62251144/131991922-c4862c22-818c-4135-8d5a-ce3250b67606.png)

How the icon should look like:
![Screenshot_20210903_123426](https://user-images.githubusercontent.com/62251144/131992120-377595f1-179b-403c-ad3f-d5764835ce7e.png)

Correct icons are used while viewing all apps.
The problem with using tray icons is that icon themes usually don't have one for every app and those are generally low res.

Using latest git version.

**Comment by prateekmedia** [comment]
This should not be the case technically can you see if it is still there in other launchers with your favourite apps?

**Comment by SubwayRunner** [comment]
To be honest it's the only launcher I had this problem with. Quite frankly some apps use wrong icons when some use right ones. 
My icon pack is flat remix blue. Maybe that can help with identifying the issue.

Also I feel like all icons used by apps in favourite label are quite 'blurry'

**Comment by prateekmedia** [comment]
Hi, I can't reproduce the same with latest Manjaro KDE, I think it's fixed somehow:

![Screenshot_20211117_144801](https://user-images.githubusercontent.com/41370460/142172272-18b9fe34-f782-410f-aab0-7cd08b57ab34.png)
