### ISSUE TITLE
FileManager and SystemSettings Buttons In Footer

### ISSUE THREAD

**Issue by Zren** [prateekmedia/Menu11#5]
As pointed out in [the screenshots on reddit](https://old.reddit.com/r/kde/comments/oc5kxh/thanks_to_uadventurous_author32_for_all_the_help/), you're missing the File Explorer and System Settings buttons next to power. It's a bit complicated to launch an app by desktop id, but it's possible. I wrote this code in TiledMenu a few years ago so there might be a simplier way but here's the ways I figured out:

a. Scan `Kicker.RootModel` for the desktop file.
b. Create a `Kicker.FavoriteModel` and scan that instead.

The file manager Dolphin has the id `org.kde.dolphin.desktop`. We should probably be using `xdg-mime`/`xdg-open` to properly open the default file manager in case it's not Dolphin but I haven't bothered to do that in Tiled Menu so it's probably not an issue.

In tiled menu, I used the `folder-open-symbolic` icon for dolphin, and `configure` icon for system settings. The `configure` icon is "two switches" using the default Breeze icon theme, it's not a "cog" icon unfortunately.

```qml
Kicker.RootModel {
	// Kicker.FavoritesModel must be a child object of RootModel.
	// appEntry.actions() looks at the parent object for parent.appletInterface and will crash plasma if it can't find it.
	// https://github.com/KDE/plasma-desktop/blob/master/applets/kicker/plugin/appentry.cpp#L151
	property var footerModel: Kicker.FavoritesModel {
		Component.onCompleted: {
			favorites = 'org.kde.dolphin.desktop,systemsettings.desktop'.split(',')
		}
	}
}
```

If you use a `Kicker.FavoriteModel`, I think you can just bind dolphin to `rootModel.footerModel.triggerIndex(0)`.

**Comment by prateekmedia** [comment]
> As pointed out in [the screenshots on reddit](https://old.reddit.com/r/kde/comments/oc5kxh/thanks_to_uadventurous_author32_for_all_the_help/), you're missing the File Explorer and System Settings buttons next to power. It's a bit complicated to launch an app by desktop id, but it's possible. I wrote this code in TiledMenu a few years ago so there might be a simplier way but here's the ways I figured out:
> 
> a. Scan `Kicker.RootModel` for the desktop file.
> b. Create a `Kicker.FavoriteModel` and scan that instead.
> 
> The file manager Dolphin has the id `org.kde.dolphin.desktop`. We should probably be using `xdg-mime`/`xdg-open` to properly open the default file manager in case it's not Dolphin but I haven't bothered to do that in Tiled Menu so it's probably not an issue.
> 
> In tiled menu, I used the `folder-open-symbolic` icon for dolphin, and `configure` icon for system settings. The `configure` icon is "two switches" using the default Breeze icon theme, it's not a "cog" icon unfortunately.
> 
> ```qml
> Kicker.RootModel {
> 	// Kicker.FavoritesModel must be a child object of RootModel.
> 	// appEntry.actions() looks at the parent object for parent.appletInterface and will crash plasma if it can't find it.
> 	// https://github.com/KDE/plasma-desktop/blob/master/applets/kicker/plugin/appentry.cpp#L151
> 	property var footerModel: Kicker.FavoritesModel {
> 		Component.onCompleted: {
> 			favorites = 'org.kde.dolphin.desktop,systemsettings.desktop'.split(',')
> 		}
> 	}
> }
> ```
> 
> If you use a `Kicker.FavoriteModel`, I think you can just bind dolphin to `rootModel.footerModel.triggerIndex(0)`.

I have a better idea, but let me try your one first, If you want you can also create a pull request or I will just do that myself.

**Comment by prateekmedia** [comment]
I have done it using Logic element which helps in running executable commands.
