### ISSUE TITLE
Use in Recommended also a more button

### ISSUE THREAD

**Issue by supervrijdag** [prateekmedia/Menu11#7]
Use also in the recommended section a more button instead of a scroll mechanism

**Windows 11:**
![afbeelding](https://user-images.githubusercontent.com/58634368/124326892-84cc9500-db87-11eb-8e58-d6896e54472e.png)

**Comment by prateekmedia** [comment]
Can you tell me what it does, I have leaked windows 11 and it doesn't have that.

**Comment by NayamAmarshe** [comment]
> Can you tell me what it does, I have leaked windows 11 and it doesn't have that.

It's for seeing more recent documents. But here we have scroll though, so I'm not sure if it's really necessary.

**Comment by supervrijdag** [comment]
https://user-images.githubusercontent.com/58634368/124348661-7748f680-dbeb-11eb-862d-a8dd58c7fa05.mp4

**Comment by prateekmedia** [comment]
> 2021-07-03.08-30-26.mp4

Ok, But as Nayam said it doesn't look necessary as we can still scroll without it, But I'll see if it needs attention or not.

**Comment by supervrijdag** [comment]
alright :)

**Comment by prateekmedia** [comment]
> alright :)

Added :D

**Comment by NayamAmarshe** [comment]
One thing though, in Windows 11 the 'More' button only appears when you fill the whole grid, not when there are only a few files in the list. So, the more button becomes redundant when you consider this.
